### ISSUE TITLE
Deploy API to Heroku or Firebase

### ISSUE THREAD

**Issue by futurethang** [UWBC-Final-Project/UWBC-Final-Project#31]
Which would be better for a team project? Need to research and perhaps add some setup for it to simulate accurately.

**Comment by futurethang** [comment]
Heroku deploy is created with Mlab installed and automatic deployment, but I need assistance with the intricacies of having the Mongoose setup communicate with the DB in the right way and how to run the seeder files. I'm researching but its a little bit of a goose chase.

**Comment by futurethang** [comment]
I'm going to make as much headway with the rest of this API while I'm trying to get it deployed, need to test it all local anyways!

**Comment by futurethang** [comment]
Latest PR #33 is a part of this objective, but does not necessarily close it just yet.

**Comment by futurethang** [comment]
With the API now launching on Heroku, I will call this done. It still needs work but is up and accessible online.

**Comment by phoebe1002** [comment]
any further action for this? should we close this issue?

**Comment by futurethang** [comment]
Yep I think we can call this all good
